[ -f $HOME/dotfiles/shell/shellrc ] && . $HOME/dotfiles/shell/shellrc
# ZSH prompt
autoload -Uz vcs_info
precmd() { vcs_info }
zstyle ':vcs_info:git:*' formats '(%b%u%c)'
setopt prompt_subst

PS1='%F{yellow}%n%f '
PS1+='%F{magenta}%~%f '
PS1+='%F{green}${vcs_info_msg_0_}%f'
PS1+=' >> '
