call plug#begin('~/.vim/plugged')

Plug 'sheerun/vim-polyglot'
Plug 'ludovicchabant/vim-gutentags'

call plug#end()

" Sensible defaults for writing text
filetype plugin indent on
set autoindent
set backspace=indent,eol,start
set smarttab
set clipboard^=unnamed
set signcolumn=yes
set shortmess+=c
set incsearch

" Sensible defaults for UI appearance
syntax enable
set termguicolors
set laststatus=2
set number
set ruler
set wildmenu
set splitright
highlight EndOfBuffer guifg=bg

" Theming
let g:material_theme_style = 'palenight'
colorscheme material

" Tweaks to speed up vim
set synmaxcol=180
set updatetime=300

" Leader key mappings
let mapleader = "'"
map <leader><leader> :source $MYVIMRC<cr>

" Brackets
inoremap " ""<left>
inoremap ' ''<left>
inoremap ( ()<left>
inoremap [ []<left>
inoremap { {}<left>
inoremap {<CR> {<CR>}<ESC>O

" Surround
vnoremap <silent> ( xi()<esc>P
vnoremap <silent> [ xi[]<esc>P
vnoremap <silent> { xi{}<esc>P
vnoremap <silent> ' xi''<esc>P
vnoremap <silent> " xi""<esc>P

" Navigation
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>
