# taps
tap "homebrew/bundle"
tap "homebrew/cask"
#tap "osx-cross/avr"

# shell tools
brew "zsh"
brew "tmux"
brew "git"
brew "wget"
brew "python"

brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "fzf"
brew "tree"

# embedded / C tools
brew "gcc"
brew "avr-gcc"
brew "avrdude"

# fun!
brew "sl"
