source ~/dotfiles/zsh/antigen.zsh

antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle ael-code/zsh-colored-man-pages 
antigen theme denysdovhan/spaceship-prompt

antigen apply
antigen cleanup

color-ssh(){
	trap "printf '\x1b]11;#292D3E\x1b\\'" INT EXIT
		printf '\x1b]11;#33384d\x1b\\'
	ssh $*
}

compdef _ssh color-ssh=ssh
alias ssh=color-ssh

alias h='cd ~/'
alias ls='ls -a -G'


alias vif='vi $(fzf-tmux -d 20%)'

export TERM=xterm-256color
