source ~/dotfiles/zsh/antigen.zsh

antigen bundle tmux-plugins/tmux-cpu

antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle ael-code/zsh-colored-man-pages 
antigen theme denysdovhan/spaceship-prompt

antigen apply
antigen cleanup

alias h='cd ~/'

if [ "$(uname 2> /dev/null)" != "Linux" ]; then
	alias ls='ls -a -G'
else 
	alias ls='ls -a --color'
fi

# FZF Setup
export FZF_DEFAULT_OPTS="--color=16 --height=20"
export FZF_DEFAULT_COMMAND='rg --files --hidden'


# True colors
export TERM=xterm-256color

# Path exports
export PATH=/usr/local/opt/llvm/bin:$PATH
